# Generated by Django 3.0.7 on 2020-10-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201001_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnswer',
            new_name='UsersAnswer',
        ),
        migrations.RenameField(
            model_name='usersanswer',
            old_name='quiztaker',
            new_name='quiz_taker',
        ),
    ]
